"""Self-healing pipeline — checks for pending error logs on startup.

v1.2.0.4: This module is imported by app.py at startup. It checks the
error log pipeline for pending (unfixed) errors and writes a structured
report to _error_logs/PENDING_FIXES.md that an AI agent or developer can
consume during software updates.

The report is generated AUTOMATICALLY whenever:
1. The app starts up and there are pending errors
2. The version changes (indicating a software update)

The developer or AI agent reads PENDING_FIXES.md, implements fixes, then
calls mark_error_fixed() for each resolved error.
"""

from __future__ import annotations

import json
import os
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

__version__ = "1.2.0.8"

_ERROR_LOG_DIR = Path(__file__).resolve().parent.parent / "_error_logs"
_PENDING_REPORT_FILE = _ERROR_LOG_DIR / "PENDING_FIXES.md"
_LAST_CHECK_FILE = _ERROR_LOG_DIR / "_last_check.json"


def _get_last_check() -> Dict[str, Any]:
    """Get the last check metadata."""
    if _LAST_CHECK_FILE.exists():
        try:
            return json.loads(_LAST_CHECK_FILE.read_text(encoding="utf-8"))
        except Exception:
            pass
    return {}


def _save_last_check(data: Dict[str, Any]) -> None:
    """Save check metadata."""
    data["timestamp"] = datetime.now().isoformat()
    try:
        _LAST_CHECK_FILE.write_text(json.dumps(data, indent=2), encoding="utf-8")
    except Exception:
        pass


def check_and_report(app_version: str) -> Optional[str]:
    """Run the self-healing check on startup.

    Called from app.py at import time. Returns a summary string if there
    are pending errors, None otherwise.

    If the app version changed since the last check (i.e., a software update
    was deployed), generates a fresh PENDING_FIXES.md report.
    """
    try:
        from utils.error_logger import get_pending_errors, generate_fix_report, get_error_summary

        last_check = _get_last_check()
        last_version = last_check.get("app_version", "")
        version_changed = last_version != app_version

        pending = get_pending_errors()
        summary = get_error_summary()

        # Always update last check
        _save_last_check({
            "app_version": app_version,
            "pending_count": len(pending),
            "total_logged": summary.get("total_logged", 0),
        })

        if not pending:
            # No pending errors — clean up report file if it exists
            if _PENDING_REPORT_FILE.exists():
                try:
                    _PENDING_REPORT_FILE.unlink()
                except Exception:
                    pass
            return None

        # Generate report if version changed or report doesn't exist
        if version_changed or not _PENDING_REPORT_FILE.exists():
            report = generate_fix_report()

            # Prepend version-change banner
            if version_changed:
                banner = (
                    f"<!-- VERSION CHANGE: {last_version} → {app_version} -->\n"
                    f"<!-- Generated: {datetime.now().isoformat()} -->\n"
                    f"<!-- This report was auto-generated by the self-healing pipeline. -->\n"
                    f"<!-- Fix each error below and call mark_error_fixed(id, version). -->\n\n"
                    f"> **Software update detected** ({last_version} → {app_version}). "
                    f"Review and fix the {len(pending)} pending error(s) below.\n\n"
                )
                report = banner + report

            try:
                _ERROR_LOG_DIR.mkdir(exist_ok=True)
                _PENDING_REPORT_FILE.write_text(report, encoding="utf-8")
            except Exception:
                pass

        return (
            f"{len(pending)} pending error(s) in error log pipeline. "
            f"See _error_logs/PENDING_FIXES.md for details."
        )

    except Exception:
        # Self-healing check must NEVER crash the app
        return None


def get_report_path() -> Path:
    """Return the path to the pending fixes report."""
    return _PENDING_REPORT_FILE
